default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: itsukaji_web_development

test:
  <<: *default
  database: itsukaji_web_test

production:
  <<: *default
  database: itsukaji_web_production
  username: itsukaji_web_production_user
  password: <%= ENV["ITSUKAJI_WEB_DATABASE_PASSWORD"] %>
  host: <%= ENV["ITSUKAJI_WEB_DATABASE_HOST"] %>
